# Generated by Django 5.1.4 on 2025-06-09 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del producto",
                        max_length=200,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable del producto",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del producto",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto",
                        max_digits=10,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="¿Está disponible para la venta?",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
                    models.Index(
                        fields=["is_active"], name="products_pr_is_acti_ca4d9a_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="products_pr_created_bce1a7_idx"
                    ),
                ],
            },
        ),
    ]
