# Generated by Django 5.1.4 on 2025-06-09 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la marca",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable de la marca",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la marca",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de la marca",
                        null=True,
                        upload_to="brands/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Sitio web oficial de la marca",
                        verbose_name="Sitio web",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="¿Está activa la marca?",
                        verbose_name="Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del atributo (ej: Color, Talla)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable del atributo",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atributo de producto",
                "verbose_name_plural": "Atributos de productos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Valor del atributo (ej: Rojo, XL)",
                        max_length=100,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable del valor",
                        max_length=100,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Código hexadecimal del color (ej: #FF0000)",
                        max_length=7,
                        verbose_name="Código de color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de atributo",
                "verbose_name_plural": "Valores de atributos",
                "ordering": ["attribute", "value"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Imagen del producto",
                        upload_to="products/gallery/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad",
                        max_length=255,
                        verbose_name="Texto alternativo",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización",
                        verbose_name="Posición",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de producto",
                "verbose_name_plural": "Imágenes de productos",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Código único de la variante",
                        max_length=50,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio específico de la variante (opcional)",
                        max_digits=10,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad disponible de esta variante",
                        verbose_name="Cantidad en stock",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Peso específico de la variante",
                        max_digits=8,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="¿Está disponible para la venta?",
                        verbose_name="Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de producto",
                "verbose_name_plural": "Variantes de productos",
                "ordering": ["product", "sku"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="allow_backorder",
            field=models.BooleanField(
                default=False,
                help_text="¿Permitir venta cuando no hay stock?",
                verbose_name="Permitir pedidos pendientes",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="compare_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio original para mostrar descuento",
                max_digits=10,
                null=True,
                verbose_name="Precio de comparación",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de costo del producto",
                max_digits=10,
                null=True,
                verbose_name="Precio de costo",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="Dimensiones del producto en centímetros",
                max_length=100,
                verbose_name="Dimensiones (L x W x H cm)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Imagen principal del producto",
                null=True,
                upload_to="products/",
                verbose_name="Imagen principal",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="¿Es un producto destacado?",
                verbose_name="Destacado",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Descripción para SEO",
                max_length=160,
                verbose_name="Meta descripción",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Título para SEO",
                max_length=60,
                verbose_name="Meta título",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="min_stock_level",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Cantidad mínima antes de avisar stock bajo",
                verbose_name="Nivel mínimo de stock",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="Descripción breve del producto",
                max_length=500,
                verbose_name="Descripción corta",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Código único del producto",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad disponible en inventario",
                verbose_name="Cantidad en stock",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="track_inventory",
            field=models.BooleanField(
                default=True,
                help_text="¿Se debe rastrear el inventario de este producto?",
                verbose_name="Rastrear inventario",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Peso del producto en kilogramos",
                max_digits=8,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Marca del producto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.brand",
                verbose_name="Marca",
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la categoría",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable de la categoría",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de la categoría",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="¿Está activa la categoría?",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoría padre para crear jerarquías",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Categoría padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría del producto",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="products_pr_is_feat_a5d7cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_pr_brand_i_dc6890_idx"),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="attribute",
            field=models.ForeignKey(
                help_text="Atributo al que pertenece este valor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="products.productattribute",
                verbose_name="Atributo",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="Producto al que pertenece la imagen",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="attribute_values",
            field=models.ManyToManyField(
                help_text="Valores de atributos que definen esta variante",
                to="products.productattributevalue",
                verbose_name="Valores de atributos",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                help_text="Producto principal",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("slug", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="productattributevalue",
            unique_together={("attribute", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together={("product", "position")},
        ),
    ]
